name: Publish Python Package

on:
  release:
    types: [published]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.8'
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install build
              pip install -r requirements.txt
          - name: Build Package
            run: python -m build
          - name: Publish Package
            run: python3 -m twine upload dist/*
            env:
              TWINE_USERNAME: __token__
              TWINE_PASSWORD: ${{secrets.PYPI_API_TOKEN}}